"""empty message

Revision ID: d992d83a493a
Revises: 
Create Date: 2018-06-29 17:21:02.797094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd992d83a493a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('area_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('pingyin', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=10), nullable=True),
    sa.Column('is_hot', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('area_id')
    )
    op.create_index(op.f('ix_area_name'), 'area', ['name'], unique=True)
    op.create_index(op.f('ix_area_parent_id'), 'area', ['parent_id'], unique=False)
    op.create_index(op.f('ix_area_pingyin'), 'area', ['pingyin'], unique=False)
    op.create_table('cinemas',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=10), nullable=True),
    sa.Column('district', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(precision=3, asdecimal=1), nullable=True),
    sa.Column('hallnum', sa.Integer(), nullable=True),
    sa.Column('servicecharge', sa.Float(precision=3, asdecimal=1), nullable=True),
    sa.Column('astrict', sa.Integer(), nullable=True),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_index(op.f('ix_cinemas_name'), 'cinemas', ['name'], unique=True)
    op.create_table('movies',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showname', sa.String(length=100), nullable=True),
    sa.Column('shownameen', sa.String(length=200), nullable=True),
    sa.Column('director', sa.String(length=100), nullable=True),
    sa.Column('leadingRole', sa.String(length=300), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('screeningmodel', sa.String(length=20), nullable=True),
    sa.Column('openday', sa.DateTime(), nullable=True),
    sa.Column('backgroundpicture', sa.String(length=100), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('mid', 'id')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('hall',
    sa.Column('hid', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mid'], ['cinemas.mid'], ),
    sa.PrimaryKeyConstraint('hid')
    )
    op.create_index(op.f('ix_hall_name'), 'hall', ['name'], unique=True)
    op.create_table('hall_schedule',
    sa.Column('hsid', sa.Integer(), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dis_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('hid', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['cinemas.mid'], ),
    sa.ForeignKeyConstraint(['hid'], ['hall.hid'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.mid'], ),
    sa.PrimaryKeyConstraint('hsid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hall_schedule')
    op.drop_index(op.f('ix_hall_name'), table_name='hall')
    op.drop_table('hall')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('movies')
    op.drop_index(op.f('ix_cinemas_name'), table_name='cinemas')
    op.drop_table('cinemas')
    op.drop_index(op.f('ix_area_pingyin'), table_name='area')
    op.drop_index(op.f('ix_area_parent_id'), table_name='area')
    op.drop_index(op.f('ix_area_name'), table_name='area')
    op.drop_table('area')
    # ### end Alembic commands ###
